### ISSUE TITLE
!!NOT USING 2 API's!!

### ISSUE THREAD

**Issue by Tarekb93** [WebAhead6/Recipinator#11]

**Comment by baderfahoum17** [comment]
yes, yet using one api for our purpose proved to be much richer, harder , and overall we learned much more from it

second api could be easily implemented(like giphy's) but this is a small grain of sand in an ocean of functionality our site provides 

id like to challenge you to present more than one search result, and for them to be clickable redirecting you to the clicked item info page!

trust me its much harder than just fetch result from an api based on one word,

goodluck

no intentions of adding the giphy api to the site at current time
