### ISSUE TITLE
CSS!!!

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/Recipinator#13]
# AMAZING JOB 🥳 

it's separated by comments, you have media query for responsiveness (although there is a bug on mobile for the form input 😅 )
clean and has a healthy amount of CSS😆 (although some parts are copy pasted)

**Comment by baderfahoum17** [comment]
indeed, some of the css is copy pasted, and manually patched
helps my not so creative mind get some ideas, all copy pasted elements are straight forward, we wouldnt use something we're not grasping fully

glad you liked the documentation, few parts at the end didnt get much attention to due time limit
