### ISSUE TITLE
no back button after choosing a meal

### ISSUE THREAD

**Issue by Tarekb93** [WebAhead6/Recipinator#16]
After searching for food query, getting all relative food, and choosing a specific meal from all. > there is no button to get back to all relative food.

**Comment by baderfahoum17** [comment]
thats actually a great idea, we didnt think of this
this should be fairly straight forward as we are saving all the results we are getting, unlike just returning just the first result like you did<3.

thats a great idea and i like the idea of implementing it, however no intentions of fixing it at this moment of time
