### ISSUE TITLE
replicateAPI and apicaller 

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/Recipinator#6]
I understand the concept of them that you don't want to surpass 5000, but instead of writing 2 identical functions (just with different url), what about adding an argument to `apiCaller` tell it to use the JSON file instead of the api  for example

```javascript
function apicaller(searchfield, flag, devMode) {

  if (devMode) {
// set a dev url 

} else {
// set a production url
}

}

```

**Comment by baderfahoum17** [comment]
brilliant idea

**Comment by bashirb** [comment]
Agreed! done.
