### ISSUE TITLE
setTimeout before fetching ?

### ISSUE THREAD

**Issue by Karyum** [WebAhead6/Recipinator#7]
[how come you have a setTimeout herehttps://github.com/WebAhead6/Recipinator/blob/master/app.js#L136], 1.5 seconds long before actually fetching ? is there an other reason than to show of the loader 😆 (which is pretty cool 😎 )

**Comment by baderfahoum17** [comment]
no, the api fetch was fast, so we never got to show the loader animation
we just wanted to flex, this was done for testing if it actually working
then left as is because we wanted it to be seen
